<a href="https://colab.research.google.com/github/vigneshpamba/24AG1A66B2/blob/main/numpyproject2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

imput numpy in python

In [1]:
import numpy as np

import numpy ccreation

In [2]:
list = [2,4,6,8,]
array1 = np.array(list)
print(array1)

[2 4 6 8]


In [3]:
array2 = np.array([2,4,6,8])
print(array2)

[2 4 6 8]


creating a 2d array


In [5]:
array3 = np.array([[1,2,3,4,5],
                  [6,7,8,9,0]])
print(array3)

[[1 2 3 4 5]
 [6 7 8 9 0]]


printing 3d array

In [15]:
array4 = np.array([[[1,2,3,4],
                    [5,6,7,8],
                  [ 0,1,2,3]],

                   [[13,14,15,16],
                    [17,18,19,20],
                    [21,32,43,54]]])
print(array4)
print(array4.ndim)
print(array4.size)
print(array4.itemsize)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 0  1  2  3]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 32 43 54]]]
3
24
8


In [ ]:
array5 = np.array([1,2,3,4,5])
print(array5.dtype)
print(array4.size)

int64


chek the datatype of given array


In [8]:
print(array5.ndim)

1


.ndim represents the dimensions of particualr array

numpy shape attribute

In [17]:
array6 = np.array([[1,2,3,4],
                  [6,7,8,9]])
print(array6.shape)

(2, 4)


In [14]:
array7 = np.array([6,7,8,9,0])
array8 = np.array([1,2,3,4,5])
print(array7.itemsize)
print(array8.itemsize)

8
8


attributr

In [18]:
array1 = np.array([1,2,3,4])
array2 = np.array([[2,3,4,5],
                   [2,3,45,5]])
print(array1.data)
print(array2.data)